### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by ASKemp** [DavidSuescunPelegay/jQuery-datatable-server-side-net-core#1]
Runs but not getting any data in the table.
Migration run and can see the data in the TestRegisters table but not getting any in the table on run, seem to be getting a js error on line 1 of app.js

Edit: works when removing $(() => {  ... }); from around the code.
Also, there's a reference to a function 'strtrunc' - is this missing? Can see it referenced in the demo at https://stackoverflow.com/questions/31809932/datatable-cell-string-truncate

**Comment by ASKemp** [comment]
Migration run and can see the data in the TestRegisters table but not getting any in the table on run.

**Comment by DavidSuescunPelegay** [comment]
Hi, sorry for my late response, I've been very busy these days.

I've been testing the issue you're addressing, I've been testing the project in 3 different computers, and works everything fine.

Please, could you send more details (screenshots, OS version, browser console version, browser version...)?

PS: I'm using Visual Studio 2019 (with Resharper Ultimate) with Firefox Developer Edition Browser (latest version).

Thanks in advance.

**Comment by DavidSuescunPelegay** [comment]
Hi @ASKemp, I've just pushed a new release, you can check it out, I think I've solved all the issues.

You can download the latest release [here](https://github.com/DavidSuescunPelegay/jQuery-datatable-server-side-net-core/releases/tag/1.2.0)
