### ISSUE TITLE
A thanks from young developer

### ISSUE THREAD

**Issue by josepherol** [DavidSuescunPelegay/jQuery-datatable-server-side-net-core#10]
Sir, I want to thank you for this public repository. I'm a very beginner (junior) backend developer and I'm trying to learn asp.net core mvc. Thanks to this pre-installed code I easily understand the Datatable mechanism. Thank you a lot...

**Comment by DavidSuescunPelegay** [comment]
Thank you very much for your message, I hope you a lucky career. You can leave a suggestion or improve it by creating a pull request, and I'll include it in a future release.
