### ISSUE TITLE
Export All Rows Is Not Working

### ISSUE THREAD

**Issue by SoftwareWajih** [DavidSuescunPelegay/jQuery-datatable-server-side-net-core#8]
I have tried to export all rows but is exporting only displayed rows it would be very helpful if anyone can address this issue thanks.

**Comment by DavidSuescunPelegay** [comment]
Hi @SoftwareWajih, I've just pushed a new release addressing the issue, now you can generate an Excel spreadsheet with all the data, with ordering and filtering support.

You can download the latest release [here](https://github.com/DavidSuescunPelegay/jQuery-datatable-server-side-net-core/releases/tag/2.0.0)

I hope you'll find useful and works fine in your environment.
